AWSTemplateFormatVersion: 2010-09-09
Description: sample s3

Parameters:
  ProjectName:
    Type: String

  Env:
    Type: String

  SampleBucketName:
    Type: String

Resources:
  S3StorageBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Disabled
      BucketName: !Sub ${Env}-${ProjectName}-${SampleBucketName}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
