name: prd-release

on:
  pull_request:
    branches:
      - prd-release

jobs:
  deploy-production:
    if: github.event.pull_request.merged == true && github.base_ref == 'prd-release'
    environment: production
    runs-on: [self-hosted]
    env:
      ENV: prd
      ProjectName: hoge
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy source
        run: |
          python deploy.py
